apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: altran-app
spec:
  selector:
    app: spring-app
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 443
  clusterIP: 10.0.171.239
  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: PUBLIC_IP_MASTER