apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: altran-app
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sping
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring
        image: 10.132.0.3:5000/hateoas:1.0
        ports:
        - containerPort: 9000
